# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'CheXinTong' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CheXinTong

pod 'YYKit', '~> 1.0.5'
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'MLInputDodger', '~> 1.4.0'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'MBProgressHUD','~>0.9.2'
pod 'AFNetworking', '~>3.1.0'
pod 'Reachability','~>3.2'
pod 'FMDB', '~> 2.6.2'
pod 'PNChart', '~> 0.8.9'
pod 'NYSegmentedControl', '~> 1.0.7'
#pod 'ReactiveCocoa','~> 4.1.0'
pod 'ReactiveObjC', '~> 2.1.0'
#pod 'ReactiveCocoa','~> 5.0.0'

  target 'CheXinTongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CheXinTongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
